
FROM node:18-alpine AS build-stage

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .


FROM node:18-alpine

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app ./


RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

EXPOSE 3000

CMD ["node", "app.js"]