apiVersion: v1
kind: Service
metadata:
  name: wordpress-service

spec:
  type: NodePort   # Exposes service on each node (VM)

  selector:
    app: wordpress   # Sends traffic to pods with this label

  ports:
    - port: 80         # Service port
      targetPort: 80   # Pod port
      nodePort: 30007  # External port (30000–32767 range)

