[servers]
server1 ansible_host=localhost ansible_port=2201 ansible_connection=ssh
server2 ansible_host=localhost ansible_port=2202 ansible_connection=ssh
server3 ansible_host=localhost ansible_port=2203 ansible_connection=ssh
server4 ansible_host=localhost ansible_port=2204 ansible_connection=ssh

[servers:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
